In [199]:
import pandas as pd 
df = pd.read_csv("data/raw_skills.csv")
print(df.head())

                    Job_Role  \
0             Data Scientist
1  Machine Learning Engineer
2                AI Engineer
3               Data Analyst
4          Backend Developer

                                              Skills
0  Python SQL Machine Learning Statistics Pandas ...
1     Python TensorFlow PyTorch Deep Learning Docker
2         Python TensorFlow NLP Deep Learning OpenCV
3               Python SQL Excel Power BI Statistics
4                  Java Spring Boot SQL REST API Git

In [200]:
print(df)
df.columns

                     Job_Role  \
0              Data Scientist
1   Machine Learning Engineer
2                 AI Engineer
3                Data Analyst
4           Backend Developer
5          Frontend Developer
6        Full Stack Developer
7              Cloud Engineer
8             DevOps Engineer
9      Cyber Security Analyst
10          Android Developer
11          Software Engineer
12     Database Administrator
13           Business Analyst
14                QA Engineer

                                               Skills
0   Python SQL Machine Learning Statistics Pandas ...
1      Python TensorFlow PyTorch Deep Learning Docker
2          Python TensorFlow NLP Deep Learning OpenCV
3                Python SQL Excel Power BI Statistics
4                   Java Spring Boot SQL REST API Git
5                 HTML CSS JavaScript React Bootstrap
6           HTML CSS JavaScript React Node.js MongoDB
7                   AWS Azure Docker Kubernetes Linux
8             Docker Kubernetes Jenkins Git Linux AWS
9          Networking Linux Python Wireshark Security
10                       Java Kotlin Android Firebase
11         Java Python Git Data Structures Algorithms
12               SQL MySQL PostgreSQL Database Backup
13                   Excel SQL Power BI Communication
14               Selenium Java Testing Automation Git

Index(['Job_Role', 'Skills'], dtype='str')

In [201]:
df.columns = df.columns.str.strip()

In [202]:
print(df.columns.tolist())

['Job_Role', 'Skills']

In [203]:
df.isnull().sum()

Job_Role    0
Skills      0
dtype: int64

In [204]:
df.shape

(15, 2)

In [205]:
df.head()

,Job_Role,Skills
0,Data Scientist,Python SQL Machine Learning Statistics Pandas ...
1,Machine Learning Engineer,Python TensorFlow PyTorch Deep Learning Docker
2,AI Engineer,Python TensorFlow NLP Deep Learning OpenCV
3,Data Analyst,Python SQL Excel Power BI Statistics
4,Backend Developer,Java Spring Boot SQL REST API Git

In [206]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [207]:
tfidf = TfidfVectorizer()

In [211]:
skill_matrix = tfidf.fit_transform(df["Skills"])

In [212]:
print(skill_matrix.shape)

(15, 52)

In [214]:
user_input = input("Enter your skills (separated by commas):")

In [215]:
user_text = user_input.replace(",", " ")

In [216]:
user_vector = tfidf.transform([user_text])

In [217]:
from sklearn.metrics.pairwise import cosine_similarity

In [218]:
similarity_scores = cosine_similarity(user_vector, skill_matrix)

In [219]:
print(similarity_scores)

[[0.67979538 0.3072367  0.29315443 0.25595364 0.115747   0.
  0.         0.         0.         0.11506259 0.         0.10981975
  0.12803466 0.14030022 0.        ]]

In [220]:
df["Similarity"] = similarity_scores.flatten()

In [222]:
print(df.columns.tolist())

['Job_Role', 'Skills', 'Similarity']

In [223]:
df[["Job_Role", "Similarity"]]

                     Job_Role  Similarity
0              Data Scientist    0.679795
1   Machine Learning Engineer    0.307237
2                 AI Engineer    0.293154
3                Data Analyst    0.255954
4           Backend Developer    0.115747
5          Frontend Developer    0.000000
6        Full Stack Developer    0.000000
7              Cloud Engineer    0.000000
8             DevOps Engineer    0.000000
9      Cyber Security Analyst    0.115063
10          Android Developer    0.000000
11          Software Engineer    0.109820
12     Database Administrator    0.128035
13           Business Analyst    0.140300
14                QA Engineer    0.000000

In [224]:
df = df.sort_values(by="Similarity", ascending=False)

In [226]:
top3 = df.head(3)
print(top3)

                    Job_Role  \
0             Data Scientist
1  Machine Learning Engineer
2                AI Engineer

                                              Skills  Similarity
0  Python SQL Machine Learning Statistics Pandas ...    0.679795
1     Python TensorFlow PyTorch Deep Learning Docker    0.307237
2         Python TensorFlow NLP Deep Learning OpenCV    0.293154

In [227]:
print(top3[["Job_Role", "Similarity"]])

                    Job_Role  Similarity
0             Data Scientist    0.679795
1  Machine Learning Engineer    0.307237
2                AI Engineer    0.293154

In [228]:
df["Match_Percentage"] = (df["Similarity"] * 100).round(2)

In [229]:
print(df[["Job_Role", "Match_Percentage"]].head(3))

                    Job_Role  Match_Percentage
0             Data Scientist             67.98
1  Machine Learning Engineer             30.72
2                AI Engineer             29.32

In [231]:
print("====== Top 3 career Recommendations =====")

for index, row in df.head(3).iterrows():
    print(f"{row['Job_Role']} --> {row['Match_Percentage']}% Match")

====== Top 3 career Recommendations =====
Data Scientist --> 67.98% Match
Machine Learning Engineer --> 30.72% Match
AI Engineer --> 29.32% Match